### ISSUE TITLE
Failed to create PortForward for service rancher: Failed to create Rustls HTTPS connector

### ISSUE THREAD

**Issue by 0123hoang** [hcavarsan/kftray#289] opened 2024-08-20 04:17 UTC
**Describe the bug**
I can not open port forward on kftray/kftui.
On newer k8s version, it works fine.

**To Reproduce**
- config.json
```json
[
    {
     "service": "rancher",
     "namespace": "cattle-system",
     "local_port": 9999,
     "remote_port": 443,
     "context": "default",
     "workload_type": "service",
     "protocol": "tcp",
     "remote_address": "127.0.0.1",
     "local_address": "127.0.0.1",
     "alias": "test",
     "domain_enabled": false,
     "kubeconfig": "/home/user/kubeconfig/port-forward.yaml"
    }
   ]
```
- When start port forward, it shows following error
![image](https://github.com/user-attachments/assets/404cf8e5-057e-41af-8858-1313cfd44222)
- When I try another k8s cluster, It works fine.
- Trace log
```log
[2024-08-20T04:12:18Z DEBUG sqlx::query] summary="SELECT id, config_id, is_running …" db.statement="\n\nSELECT\n  id,\n  config_id,\n  is_running\nFROM\n  config_state\n" rows_affected=0 rows_returned=1 elapsed=39.309µs elapsed_secs=3.9309e-5
[2024-08-20T04:12:18Z DEBUG sqlx::query] summary="SELECT id, data FROM …" db.statement="\n\nSELECT\n  id,\n  data\nFROM\n  configs\n" rows_affected=0 rows_returned=1 elapsed=39.375µs elapsed_secs=3.9375e-5
[2024-08-20T04:12:18Z DEBUG kftray_portforward::core] Remote Port: 443
[2024-08-20T04:12:18Z DEBUG kftray_portforward::core] Local Port: 9999
[2024-08-20T04:12:18Z INFO  kftray_portforward::core] Attempting to forward to service: Some("rancher")
[2024-08-20T04:12:18Z INFO  kftray_portforward::client] Trying kubeconfig path: "/home/user/kubeconfig/port-forward.yaml"
[2024-08-20T04:12:18Z INFO  kftray_portforward::client] Successfully read kubeconfig from "/home/user/kubeconfig/port-forward.yaml"
[2024-08-20T04:12:18Z INFO  kftray_portforward::client] Available contexts: ["default"]
[2024-08-20T04:12:18Z INFO  kftray_portforward::client] Successfully created configuration for context: default
[2024-08-20T04:12:18Z INFO  kftray_portforward::client] Failed to create Rustls HTTPS connector for "/home/user/kubeconfig/port-forward.yaml": Failed to create Rustls HTTPS connector
[2024-08-20T04:12:18Z ERROR kftray_portforward::core] Failed to create PortForward for service rancher: Unable to create client with any of the provided kubeconfig paths: Failed to create Rustls HTTPS connector for "/home/user/kubeconfig/port-forward.yaml": Failed to create Rustls HTTPS connector
```
**Expected behavior**
Open forward successully.

**Additional context**
- **K8s version** : v1.21.11
-  **K8s version with no error**: v1.28.11

**Comment by hcavarsan** [comment] 2024-08-25 23:17
Thank you for the report, @0123hoang . I'm on it.

**Comment by hcavarsan** [comment] 2024-08-26 04:00
@0123hoang  can you try to see if its ok now?

https://github.com/hcavarsan/kftray/releases/tag/v0.13.3

**Comment by 0123hoang** [comment] 2024-08-27 04:46
I got a problem with key size
```
[2024-08-27T04:38:40Z DEBUG kftray_portforward::core] Remote Port: 443
[2024-08-27T04:38:40Z DEBUG kftray_portforward::core] Local Port: 9999
[2024-08-27T04:38:40Z INFO  kftray_portforward::core] Attempting to forward to service: Some("rancher")
[2024-08-27T04:38:40Z INFO  kftray_portforward::client] Using provided kubeconfig paths: /home/kubeconfig/port-forward.yaml
[2024-08-27T04:38:40Z INFO  kftray_portforward::client] Attempting to read kubeconfig from path: "/home/kubeconfig/port-forward.yaml"
[2024-08-27T04:38:40Z INFO  kftray_portforward::client] Successfully read kubeconfig from "/home/kubeconfig/port-forward.yaml"
[2024-08-27T04:38:40Z INFO  kftray_portforward::client] Available contexts in "/home//kubeconfig/port-forward.yaml": ["default"]
[2024-08-27T04:38:40Z INFO  kftray_portforward::client] Creating configuration for context: default
[2024-08-27T04:38:40Z INFO  kftray_portforward::client] Successfully created configuration for context: default
[2024-08-27T04:38:40Z INFO  kftray_portforward::client] Attempting to create client with OpenSSL HTTPS connector.
[2024-08-27T04:38:40Z WARN  kftray_portforward::client] Failed to create OpenSSL HTTPS connector: openssl tls error: failed to create OpenSSL SSL connector: failed to set the leaf certificate: error:0A00018F:SSL routines:SSL_CTX_use_certificate:ee key too small:ssl/ssl_rsa.c:239:
[2024-08-27T04:38:40Z INFO  kftray_portforward::client] Attempting to create client with Rustls HTTPS connector.
[2024-08-27T04:38:40Z DEBUG hyper_rustls::config] with_native_roots processed 138 valid and 0 invalid certs
[2024-08-27T04:38:40Z ERROR kftray_portforward::client] Failed to create Rustls HTTPS connector: rustls tls error: invalid private key: unexpected error: failed to parse private key as RSA, ECDSA, or EdDSA
[2024-08-27T04:38:40Z WARN  kftray_portforward::client] Failed to create HTTPS connector for context: default
[2024-08-27T04:38:40Z ERROR kftray_portforward::core] Failed to create PortForward for service rancher: Unable to create client with any of the provided kubeconfig paths: Failed to create HTTPS connector for context: default
```

**Comment by hcavarsan** [comment] 2024-09-07 19:24
Hey @0123hoang, I am trying to simulate the error but I am not able to reproduce. These are the steps I followed:

- I installed Rancher Docker Desktop version 1.15.1 and set up a Kubernetes cluster with version 1.21.11:
![CleanShot 2024-09-07 at 16 02 10](https://github.com/user-attachments/assets/72b11ecf-b3ef-42f9-ba84-fc0c12b178fa)

- I moved the cluster context configuration to a separate kubeconfig file:
```bash
kubectl config view --minify --flatten --context=rancher-desktop > $HOME/rancher-desktop-context.yaml
```

- I installed the Rancher cattle-system:
```bash
helm repo add rancher-stable https://releases.rancher.com/server-charts/stable

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.crds.yaml

helm install cert-manager jetstack/cert-manager \
    --namespace cert-manager \
    --create-namespace \
    --set crds.enabled=true --version v1.10

helm install rancher rancher-stable/rancher \
    --namespace cattle-system \
    --set hostname=rancher.my.org \
    --set bootstrapPassword=admin
```

![CleanShot 2024-09-07 at 16 15 34](https://github.com/user-attachments/assets/7b6e742b-9e12-4691-adec-2f3bd8a7a545)

- I configured port forwarding for this service in kftray:
![CleanShot 2024-09-07 at 16 17 04](https://github.com/user-attachments/assets/3ce9e187-fc7e-4430-914f-1dc236608d4b)

```json
[
    {
        "service": "rancher",
        "namespace": "cattle-system",
        "local_port": 9999,
        "remote_port": 80,
        "context": "rancher-desktop",
        "workload_type": "service",
        "protocol": "tcp",
        "alias": "test",
        "kubeconfig": "/Users/henrique/rancher-desktop-context.yaml"
    }
]
```

- I started the service via kftray and kftui successfully and accessed it via UI:
![CleanShot 2024-09-07 at 16 18 06](https://github.com/user-attachments/assets/292a2a12-130c-49c2-bbc8-1385234cf9b4)

![CleanShot 2024-09-07 at 16 20 41](https://github.com/user-attachments/assets/fdafdf5a-85e3-4498-a9fd-79d776e228c8)

![CleanShot 2024-09-07 at 16 18 28](https://github.com/user-attachments/assets/a4f85e77-e51d-41d2-aa2f-c6c052b60f69)

Just for the record, this is the kubeconfig:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1.....
    server: https://127.0.0.1:6443
  name: rancher-desktop
contexts:
- context:
    cluster: rancher-desktop
    user: rancher-desktop
  name: rancher-desktop
current-context: rancher-desktop
kind: Config
preferences: {}
users:
- name: rancher-desktop
  user:
    client-certificate-data: LS0tLS1CRUdJTi.....
    client-key-data: LS0tLS1CR.....
```

As I mentioned, the process started successfully... Am I missing any steps? Or is there any other specificity in your setup that I can simulate to reproduce the error?

Thank you.

**Comment by hcavarsan** [comment] 2024-09-14 22:28
@0123hoang  can you try to see if its ok now? i made some fixes and improvements in this flow

https://github.com/hcavarsan/kftray/releases/tag/v0.14.1

**Comment by hcavarsan** [comment] 2024-09-22 01:37
i think the issue should be fixed now. if you still run into the problem, just reopen this issue and i'll keep looking into it. thanks a lot for the report!

**Closed by hcavarsan** 2024-09-22 01:37 UTC
Labels: bug
